name: metaimm
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip=24.0
  - numpy=1.23.5
  - scipy=1.10.1
  - pandas=1.5.3
  - anndata=0.8.0
  - h5py=3.8.0
  - scanpy=1.9.1
  - matplotlib=3.7.1
  - scikit-learn=1.2.2
  - statsmodels=0.14.0
  - pytables=3.8.0
  - numba=0.57.1
  - jupyterlab=4.0.5
  - r-base=4.3.2          # ensure R available inside the same env
  - r-renv
  - r-devtools
  - r-irkernel
  - r-essentials
  - r-rjson
  - r-reticulate
  - r-seurat
  - r-seuratobject
  - r-ggplot2
  - r-dplyr
  - r-readr
  - r-tibble
  - r-matrix
  - r-data.table
  - r-patchwork
  - r-cowplot
  - r-remotes
  - r-biocmanager
  - r-gsva
  - pip:
      - squidpy==1.2.2
      - tangram-sc==1.0.3
      - scvi-tools==1.0.3
      - session-info==1.0.0
      - anndata2ri==1.3.2
      - pyreadr==0.5.0
